//1 Nisan Cumartesi Dersi..

System.debug('Batch 16 Merhaba');
System.debug('Bugun hava cok guzel');

string city; //declare
System.debug(city);
string country = ''; //bos degeri tanimlama
System.debug(country);
string region = 'America'; //tanimlama
System.debug(region);
string sehir = 'istanbul';
string text = 'Turkiyenin en kalabalik sehri ' + sehir;
System.debug(text);

//50 sayisini yazdiralim
integer sayi1 = 50;
System.debug(sayi1);
integer sayi2 = 50/2;
System.debug(sayi2);
Boolean isActive = True;
System.debug(isActive);

Boolean cond1 = 5>3;
System.debug('5>3 mu? ==> ' + cond1);

Boolean cond2 = 11>100;
System.debug('11>100 mu? => ' + cond2);
