

String carBrand = 'Volkswagen';
system.debug(carBrand);

String carModel = 'Polo';
system.debug(carModel);

String carColor = 'Beyaz';
system.debug(carColor);

String together = carBrand + ' ' + carModel + ' ' + carColor;
system.debug(together);*/

String favCity = 'Tokyo';
system.debug(favCity);

String favFilm = 'Matrix';
system.debug(favFilm);

String favSeason = 'Ilkbahar';
system.debug(favSeason);