public class Car {
	//this is a class body
	
	//public is access modifier
	//void isreturn type
	//switchOn is METHOD NAME (or Function Name)
	
    public void switchOn(){
        //this is method body
        system.debug('starting the carrr nowww');
        
    }
    
    //can we have more than one method in a class?
    public void switchOff(){
        system.debug('switching off car');
    }
}